# Data Wrangling: Join, Combine, and Reshape

### Hierarchical Indexing

In [3]:
import numpy as np
import pandas as pd

In [12]:
data = pd.Series(np.random.randn(9),
                 index=[
                        ['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]
                       
                       ])
data

a  1    0.706573
   2   -0.610451
   3   -0.561792
b  1   -0.613668
   3   -0.297383
c  1    0.964981
   2    0.991413
d  2    0.047090
   3   -0.620089
dtype: float64

In [10]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [13]:
data.values

array([ 0.70657297, -0.61045135, -0.56179236, -0.61366798, -0.29738301,
        0.96498091,  0.99141306,  0.04709029, -0.62008894])

In [14]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],['Green', 'Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [20]:
ar1d = np.array([1,2,3,4,5,6,7,8])

In [22]:
ar1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
type(ar1d)

numpy.ndarray

In [24]:
ar1d.ndim

1

In [25]:
arr2d = np.array([[1,2,3,4,5,6,7,8],
                  [2,3,4,5,6,7,8,9],
                 [3,4,5,6,7,8,9,10]])

In [26]:
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [27]:
arr2d.ndim

2

In [28]:
arr2d.shape

(3, 8)

In [37]:
arr2d = np.arange(16).reshape(16,1)
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [38]:
arr2d.shape

(16, 1)

In [43]:
arr3d = np.arange(27).reshape(3,3,3)# (copy, row, cols)

In [44]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
arr3d = np.arange(12).reshape(2,1,6)
arr3d

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [47]:
ar1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
ar1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
ar1d.min()

1

In [50]:
ar1d.max()

8

In [51]:
ar1d.mean()

4.5

In [52]:
ar1d.std()

2.29128784747792

In [53]:
lst = [1,2,3,4]
lst_10 = []
for n in lst:
    lst_10.append(n*10)
lst_10

[10, 20, 30, 40]

In [54]:
arr = np.array(lst)

In [55]:
arr*10

array([10, 20, 30, 40])

In [56]:
arr3d/100

array([[[0.  , 0.01, 0.02, 0.03, 0.04, 0.05]],

       [[0.06, 0.07, 0.08, 0.09, 0.1 , 0.11]]])

In [14]:
arr2d_a = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,22,33,44,55]])
arr2d_b  =np.array([[2,4,6,8,10],[10,8,6,4,2],[9,8,7,6,54]])
arr2d_c = np.arange(25).reshape(5,5)
arr2d_c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
arr2d_b

array([[ 2,  4,  6,  8, 10],
       [10,  8,  6,  4,  2],
       [ 9,  8,  7,  6, 54]])

In [8]:
arr2d_a * arr2d_b # * mirror multiplication

array([[   2,    8,   18,   32,   50],
       [  60,   56,   48,   36,   20],
       [  99,  176,  231,  264, 2970]])

In [7]:
arr2d_a + arr2d_b

array([[  3,   6,   9,  12,  15],
       [ 16,  15,  14,  13,  12],
       [ 20,  30,  40,  50, 109]])

In [6]:
arr2d_a.shape, arr2d_c.shape

((3, 5), (5, 5))

In [15]:
arr2d_a *  arr2d_c

ValueError: operands could not be broadcast together with shapes (3,5) (5,5) 

In [16]:
arr2d_a@arr2d_c

array([[ 200,  215,  230,  245,  260],
       [ 450,  490,  530,  570,  610],
       [2200, 2365, 2530, 2695, 2860]])

In [17]:
np.linalg.inv(arr2d_c)

LinAlgError: Singular matrix

In [18]:
data = pd.read_excel("test_data.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'test_data.xlsx'

In [88]:
df0 = pd.read_excel("test_data.xlsx")
df1 = pd.read_excel("test_data.xlsx",sheet_name=1)
df2 = pd.read_excel("test_data.xlsx",sheet_name=2)

In [89]:
df0

sales_man_id sales_man_name sales_man_city  product_id manager
0             1           Asad        Karachi         123   Jawed
1             2         Sumair         Lahore         123   Jawed
2             3         Farjad        Karachi         145   Najam
3             4         Hassan         Lahore         567   Najam
4             5          Nasir      Hyderabad         234   Jawed
5             6         Kashif      Hyderabad         234  Faisal
6             7           Sana         Lahore         567  Faisal
7             8         Fatima        Karachi         345   Najam
8             9       Abdullah        Karachi         123  Faisal

In [90]:
df1

sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1          Ahmed        Karachi         123   Jawed           2
1             22           Umer         Lahore         123   Jawed           3
2             33        Huzaifa        Karachi         145   Najam           4
3              4           Asad         Lahore         567   Najam           5
4             55        Hussain      Hyderabad         234   Jawed           6
5             66            Ali      Hyderabad         234  Faisal           7
6             77          Sadaf         Lahore         567  Faisal           8
7             88          Kiran        Karachi         345   Najam           9
8             99            Ali        Karachi         123  Faisal           1
9            101           Asad      Hyderabad         432   Jawed           4
10           101           Asad      Hyderabad         432   Jawed           5

In [91]:
df2

sales_man_name Region   Sales  Amount 
0           Asad       A    100   100000
1        Hussain       B    300   450000
2            Ali       C    234   125000
3           Sana       D    231   652000
4        Fatima        E    324   145000
5         Kashif       F    123   825000
6         Hassan       G    129   125000
7          Almas       H    345   325600
8          Fahan       I    400   895200

In [94]:
concatenated_data =pd.concat([df0,df1])
concatenated_data.reset_index(drop=True,inplace=True)

In [95]:
concatenated_data

sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1           Asad        Karachi         123   Jawed         NaN
1              2         Sumair         Lahore         123   Jawed         NaN
2              3         Farjad        Karachi         145   Najam         NaN
3              4         Hassan         Lahore         567   Najam         NaN
4              5          Nasir      Hyderabad         234   Jawed         NaN
5              6         Kashif      Hyderabad         234  Faisal         NaN
6              7           Sana         Lahore         567  Faisal         NaN
7              8         Fatima        Karachi         345   Najam         NaN
8              9       Abdullah        Karachi         123  Faisal         NaN
9              1          Ahmed        Karachi         123   Jawed         2.0
10            22           Umer         Lahore         123   Jawed         3.0
11            33        Huzaifa        Karachi         145   Najam         4.0
12             4           Asad         Lahore         567   Najam         5.0
13            55        Hussain      Hyderabad         234   Jawed         6.0
14            66            Ali      Hyderabad         234  Faisal         7.0
15            77          Sadaf         Lahore         567  Faisal         8.0
16            88          Kiran        Karachi         345   Najam         9.0
17            99            Ali        Karachi         123  Faisal         1.0
18           101           Asad      Hyderabad         432   Jawed         4.0
19           101           Asad      Hyderabad         432   Jawed         5.0

In [96]:
concatenated_data =pd.concat([df0,df1],axis=1)
concatenated_data.reset_index(drop=True,inplace=True)

In [97]:
concatenated_data

sales_man_id sales_man_name sales_man_city  product_id manager  \
0            1.0           Asad        Karachi       123.0   Jawed   
1            2.0         Sumair         Lahore       123.0   Jawed   
2            3.0         Farjad        Karachi       145.0   Najam   
3            4.0         Hassan         Lahore       567.0   Najam   
4            5.0          Nasir      Hyderabad       234.0   Jawed   
5            6.0         Kashif      Hyderabad       234.0  Faisal   
6            7.0           Sana         Lahore       567.0  Faisal   
7            8.0         Fatima        Karachi       345.0   Najam   
8            9.0       Abdullah        Karachi       123.0  Faisal   
9            NaN            NaN            NaN         NaN     NaN   
10           NaN            NaN            NaN         NaN     NaN   

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience  
0              1          Ahmed        Karachi         123   Jawed           2  
1             22           Umer         Lahore         123   Jawed           3  
2             33        Huzaifa        Karachi         145   Najam           4  
3              4           Asad         Lahore         567   Najam           5  
4             55        Hussain      Hyderabad         234   Jawed           6  
5             66            Ali      Hyderabad         234  Faisal           7  
6             77          Sadaf         Lahore         567  Faisal           8  
7             88          Kiran        Karachi         345   Najam           9  
8             99            Ali        Karachi         123  Faisal           1  
9            101           Asad      Hyderabad         432   Jawed           4  
10           101           Asad      Hyderabad         432   Jawed           5

In [99]:
concatenated_data.to_excel("reqdata.xlsx")